version: '3.8'

services:
  app:
    build: .
    container_name: php-app
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: iset
      DB_USER: root
      DB_PASSWORD: root
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iset
    volumes:
      - db_data:/var/lib/mysql
      - ./apache.conf:/etc/apache2/apache2.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:

